### ISSUE TITLE
docker-compose up command failing for nest-book-example_api_1

### ISSUE THREAD

**Issue by saudar82** [backstopmedia/nest-book-example#29]
While running docker-compose up command, the nest-book-example_api_1 container is failing with the below error:

api_1       | npm ERR! path /app/package.json
api_1       | npm ERR! code ENOENT
api_1       | npm ERR! errno -2
api_1       | npm ERR! syscall open
api_1       | npm ERR! enoent ENOENT: no such file or directory, open '/app/package.json'
api_1       | npm ERR! enoent This is related to npm not being able to find a file.
api_1       | npm ERR! enoent
api_1       |
api_1       | npm ERR! A complete log of this run can be found in:
api_1       | npm ERR!     /root/.npm/_logs/2019-10-01T17_44_52_053Z-debug.log
nest-book-example_api_1 exited with code 254

**Comment by adrien2p** [comment]
Hey, thanks for your report,

Did you had a look on that issue https://github.com/backstopmedia/nest-book-example/issues/27 ?

**Comment by saudar82** [comment]
Yes it worked, Thank you
